# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1728e0183783d3b234f6dbeb4f92c919a280ac6b9099dbc0f2def0a43dafa5a3cf11b0fd4bf79c5279268e5b7b6b030d584ed174a262bf6627d111f8334a7d27

test:
  secret_key_base: bff64e5320cd19601b77015a1005a40932d898c483487ec9d7885fda307f93c754e9931d18e959283787333e82d287e9c4d8b31320c4c5c62e2212f109ed1c28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
